### ISSUE TITLE
package name with @ build error

### ISSUE THREAD

**Issue by d0whc3r** [kazupon/vue-cli-plugin-p11n#10]
When I try to build a plugin with package name like: `@something/plugin-name` it will build into folder `dist/@something/plugin-name`.
Could `@something` be ignored?

Thank you very much

**Comment by EvanBurbidge** [comment]
Is there ever a case where a name may contain multiple forward slash characters e.g. `@namespace/myPlugin/test` ? @d0whc3r

**Comment by d0whc3r** [comment]
I have never seen any package like that and in npmjs documentation is not contempled. https://docs.npmjs.com/about-scopes

**Comment by EvanBurbidge** [comment]
True, just wondering if a str.includes would do the job or should we do a recursive search from the index of @ character to the index of the first / character.

**Comment by EvanBurbidge** [comment]
@kazupon small pr there if you want to try it out.

**Comment by kazupon** [comment]
merged #10, and release v0.1.3!

**Comment by d0whc3r** [comment]
it si not working :cry:
