### ISSUE TITLE
Want to build demo

### ISSUE THREAD

**Issue by miyanokomiya** [kazupon/vue-cli-plugin-p11n#34]
I am developing a library of UI components, and create some demo for explaining how to use.
I want to build the demo and publish it on githubpages. However, there is no way to build the demo, since the command 'vue-cli-service build' never accept any args.

Is there any way to build demo? If not, it's a feature request.

```sh
$ yarn vue-cli-service demo:build
```
For example, executing as above and generate static bundled demo to demo/dist.

**Comment by kazupon** [comment]
I've released v0.4.0 :)

**Comment by rwwagner90** [comment]
How are we supposed to use the demo? `yarn demo` does not serve it and we have no App entry point in the demo folder. I am quite confused.
